"""empty message

Revision ID: 36b5f1ed6fa6
Revises: b8592062a8b3
Create Date: 2020-02-22 21:06:37.686999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b5f1ed6fa6'
down_revision = 'b8592062a8b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beta_email_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beta_email_subscribers_email'), 'beta_email_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_beta_email_subscribers_first_name'), 'beta_email_subscribers', ['first_name'], unique=False)
    op.create_index(op.f('ix_beta_email_subscribers_last_name'), 'beta_email_subscribers', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beta_email_subscribers_last_name'), table_name='beta_email_subscribers')
    op.drop_index(op.f('ix_beta_email_subscribers_first_name'), table_name='beta_email_subscribers')
    op.drop_index(op.f('ix_beta_email_subscribers_email'), table_name='beta_email_subscribers')
    op.drop_table('beta_email_subscribers')
    # ### end Alembic commands ###
